### ISSUE TITLE
Only detect changes from the last commit

### ISSUE THREAD

**Issue by mowies** [ksindi/buildpipe#40]
This is not really an issue but more of a request for help.

I am not sure if this can be easily done with this repo, but I want to detect changes for a project only if the **latest** commit had changes in the respective project's files.

Is this somehow possible with buildpipe?

I only found this block where the `git log` command actually does what I need, but only on the deploy branch or master.
```
if branch == deploy_branch:
    command = ['git', 'log', '-m', '-1', '--name-only', '--pretty=format:', commit]
else:
    command = ['git', 'whatchanged', '--name-only', '--pretty=format:', 'origin..HEAD']
```

**Comment by ksindi** [comment]
@mowies The block above would indeed need to be modified. This SO answer can get you started if you want to make a PR: https://stackoverflow.com/a/6584048/690430.

Out of curiosity why would one want to do this? I'm hesitant to add this feature unless there's a common use case.

**Comment by mowies** [comment]
I use this repo to detect changes in a monorepo with several projects as subfolders. But the builds steps that I generate only trigger other pipelines that are specific to one of the projects in the monorepo to have a more static approach to pipelines instead of building different projects in the same pipeline which ever changing steps.

So to trigger the correct pipeline I need to check if the latest commit changed something in the respective project folder from the monorepo.

**Comment by mowies** [comment]
It needs to be added that the monorepo pipeline running buildpipe gets triggered for every commit

**Comment by ksindi** [comment]
Understood. I can see this as a valid feature for the CI part but not upon merge for CD since you want everything to deploy. Is that correct?

**Comment by mowies** [comment]
You're right yes. I'm imagining something like a setting to choose whether you want to detect changes from the whole branch or just from the last commit

**Comment by ksindi** [comment]
Feel free to make a PR.

**Comment by mowies** [comment]
The git command I would use to get the changes of the latest commit is:
`git log -m -1 --name-only --pretty=format: HEAD~1..HEAD`

Any other suggestions or ideas from you?

**Comment by mowies** [comment]
After looking into this a bit further I would go with a solution where you can configure the revision range from the `buildpipe.yml` file either for each project separately or for the complete pipeline.

**Comment by ksindi** [comment]
Yeah I can see it as a top level key e.g. `last_commit_only: true` (need a better name) that can act as a flag for the behavior you want. Feel free to make a PR.
