### ISSUE TITLE
Provide version info with flag

### ISSUE THREAD

**Issue by mowies** [ksindi/buildpipe#44]
buildpipe does not have the `--version` flag in place.
Since users call buildpipe directly from the command line I think this flag should be supported.

**Comment by ksindi** [comment]
Makes sense @mowies. Let me know if you have time for a small PR on that.

**Comment by mowies** [comment]
I will have time for this next week I think

**Comment by chagui** [comment]
@mowies if you don't let me know, I'll be more than happy to pick this up!

**Comment by mowies** [comment]
Sure, feel free to do it!
